version: '3.4'
services:
  easy-ssb-pub:
    image: easy_ssb_pub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8008:8008"
      - "8007:8007"
    volumes:
      - .:/easy_ssb_pub
    container_name: easy-ssb-pub
    restart: unless-stopped
    env_file: .env
    command: npm run start
